/*SAMPLE DATA GENERATOR*/
    create global TEMPORARY table temp_table1 /*TEMP TABLE FOR ORGANISER, RESELLER, EVENT TABLES*/
    ON COMMIT PRESERVE ROWS
    AS
    select DISTINCT a.ORGANISER_ID, a.ORGANISER_NAME, a.RESELLER_ID, a.RESELLER_NAME, a.ORGANISERRESELLER_ID, a.EVENT_ID, a.TICKET_COUNT, a.COMMISSIONPERC from
    (
    select round(DBMS_RANDOM.value(100,999)) ORGANISER_ID, DBMS_RANDOM.string('A',5) ORGANISER_NAME, round(DBMS_RANDOM.value(1000,9999)) RESELLER_ID, DBMS_RANDOM.string('A',5) RESELLER_NAME, round(DBMS_RANDOM.value(10000,99999)) ORGANISERRESELLER_ID, DBMS_RANDOM.string('X',4) EVENT_ID, round(DBMS_RANDOM.value(0,1000)) TICKET_COUNT, round(DBMS_RANDOM.value(0,100)) COMMISSIONPERC 
    from dual
    connect by level <= 1000
    ) a
    where rownum <= 10;

    /*TEMP TABLE FOR TICKETS AND CUSTOMER TABLES*/
    create global TEMPORARY table temp_table2
    ON COMMIT PRESERVE ROWS
    AS
    select DISTINCT b.TICKET_ID,b.TICKET_PRICE, b.CUSTOMER_ID, b.CUSTOMER_NAME, b.PURCHASE_DATE from
    (
    select DBMS_RANDOM.string('X',5) TICKET_ID, round(DBMS_RANDOM.value(100,500)) TICKET_PRICE, DBMS_RANDOM.string('L',9) CUSTOMER_ID, DBMS_RANDOM.string('L',5) CUSTOMER_NAME, TRUNC(SYSDATE - DBMS_RANDOM.value(0,366)) AS PURCHASE_DATE
    from dual
    connect by level <= 1000
    ) b
    where rownum <=1000;

    insert into TABLEEVENT(EVENT_ID,TICKET_COUNT) SELECT EVENT_ID,TICKET_COUNT FROM temp_table1;
    insert into TABLEORGANISER(ORGANISER_ID,ORGANISER_NAME) SELECT ORGANISER_ID,ORGANISER_NAME FROM temp_table1;
    insert into TABLERESELLER(RESELLER_ID,RESELLER_NAME) SELECT RESELLER_ID,RESELLER_NAME FROM temp_table1;
    insert into TORGANISERRESELLER(ORGANISERRESELLER_ID,ORGANISER_ID,RESELLER_ID,EVENT_ID,COMMISSIONPERC) SELECT ORGANISERRESELLER_ID,ORGANISER_ID,RESELLER_ID,EVENT_ID,COMMISSIONPERC FROM temp_table1;
    insert into TABLETICKETS(TICKET_ID,PURCHASE_DATE,TICKET_PRICE) SELECT TICKET_ID,PURCHASE_DATE,TICKET_PRICE FROM temp_table2;
    insert into TABLECUSTOMER(CUSTOMER_ID,CUSTOMER_NAME,TICKET_ID) SELECT CUSTOMER_ID,CUSTOMER_NAME,TICKET_ID FROM temp_table2;

    /*Queries to create join conditions, ASSUMING ORGANISER 111 SELLS TICKETS THROUGH RESELLER 1111 AND RESELLER 2222 FOR EVENT ZZZZ - RESELLER 1111 IS ASSIGNED 200 TICKETS AND RESELLER 2222 IS ASSIGNED 200 TICKETS*/
    insert into TABLEORGANISER(ORGANISER_ID, ORGANISER_NAME) values ('111','Aaaaa');
    insert into TABLERESELLER(RESELLER_ID, RESELLER_NAME) values ('1111','Bbbbb');
    insert into TABLERESELLER(RESELLER_ID, RESELLER_NAME) values ('2222','Ccccc');
    insert into TABLEEVENT(EVENT_ID,TICKET_COUNT) values ('ZZZZ',400);
    insert into TORGANISERRESELLER(ORGANISERRESELLER_ID, ORGANISER_ID, RESELLER_ID, EVENT_ID, COMMISSIONPERC) values ('11111','111','1111','ZZZZ',10);
    insert into TORGANISERRESELLER(ORGANISERRESELLER_ID, ORGANISER_ID,RESELLER_ID, EVENT_ID, COMMISSIONPERC) values ('22222','111','2222','ZZZZ',15);

    UPDATE TABLETICKETS
    SET ORGANISERRESELLER_ID = '11111'
    WHERE ROW_ID BETWEEN 0 AND 199;

    UPDATE TABLETICKETS
    SET ORGANISERRESELLER_ID = '22222'
    WHERE ROW_ID BETWEEN 200 AND 399;
/*
delete from torganiserreseller;
delete from tableorganiser;
delete from tablereseller;
delete from TABLEEVENT;
delete from TABLECUSTOMER;
delete from TABLETICKETS;
truncate table temp_table1;
drop table temp_table1;
truncate table temp_table2;
drop table temp_table2;
*/