CREATE MATERIALIZED VIEW LOG ON TABLEORGANISER;
CREATE MATERIALIZED VIEW LOG ON TABLERESELLER;
CREATE MATERIALIZED VIEW LOG ON TORGANISERRESELLER;
CREATE MATERIALIZED VIEW LOG ON TABLECUSTOMER;
CREATE MATERIALIZED VIEW LOG ON TABLEEVENT;
CREATE MATERIALIZED VIEW LOG ON TABLETICKETS;

CREATE MATERIALIZED VIEW mv1 
  REFRESH FAST NEXT SYSDATE 
  AS SELECT * FROM TABLEORGANISER;
  
  CREATE MATERIALIZED VIEW mv2 
  REFRESH FAST NEXT SYSDATE 
  AS SELECT * FROM TABLERESELLER;
  
  CREATE MATERIALIZED VIEW mv3 
  REFRESH FAST NEXT SYSDATE 
  AS SELECT * FROM TORGANISERRESELLER;
  
  CREATE MATERIALIZED VIEW mv4 
  REFRESH FAST NEXT SYSDATE 
  AS SELECT * FROM TABLECUSTOMER;
  
  CREATE MATERIALIZED VIEW mv5 
  REFRESH FAST NEXT SYSDATE 
  AS SELECT * FROM TABLEEVENT;
  
  CREATE MATERIALIZED VIEW mv6 
  REFRESH FAST NEXT SYSDATE 
  AS SELECT * FROM TABLETICKETS;
  
