/*get the number of available tickets per each possible sales company*/
select b.RESELLER_ID, RESELLER_NAME, a.TOTAL_TICKETS from 
(
SELECT ORGANISERRESELLER_ID, COUNT(TICKET_ID) AS TOTAL_TICKETS FROM TABLETICKETS
GROUP BY ORGANISERRESELLER_ID
) a
INNER JOIN
TORGANISERRESELLER b
on a.ORGANISERRESELLER_ID = b.ORGANISERRESELLER_ID
INNER JOIN
TABLERESELLER c
ON b.RESELLER_ID = c.RESELLER_ID;

/*provide stats for each organizer to explain which resellers are doing the best work*/
select c.ORGANISER_ID, c.ORGANISER_NAME, b.RESELLER_ID, a.TOTAL_TICKETS, b.COMMISSIONPERC from 
(
SELECT ORGANISERRESELLER_ID, COUNT(TICKET_ID) AS TOTAL_TICKETS FROM TABLETICKETS
GROUP BY ORGANISERRESELLER_ID
) a
INNER JOIN
TORGANISERRESELLER b
on a.ORGANISERRESELLER_ID = b.ORGANISERRESELLER_ID
INNER JOIN
TABLEORGANISER c
on b.ORGANISER_ID = c.ORGANISER_ID
ORDER BY TOTAL_TICKETS DESC;


/*commissioning report for each reseller per month and event*/
SELECT a.TICKET_ID,a.TICKET_PRICE, (a.TICKET_PRICE*b.COMMISSIONPERC) COMMISSION ,b.ORGANISERRESELLER_ID, a.PURCHASE_DATE, b.ORGANISER_ID, b.RESELLER_ID, b.EVENT_ID, b.COMMISSIONPERC
FROM TABLETICKETS a
INNER JOIN
TORGANISERRESELLER b
on a.ORGANISERRESELLER_ID = b.ORGANISERRESELLER_ID;


SELECT a.TICKET_ID,a.TICKET_PRICE, (a.TICKET_PRICE*b.COMMISSIONPERC) COMMISSION, b.ORGANISERRESELLER_ID, EXTRACT(month FROM a.PURCHASE_DATE) PURCHASE_MONTH, b.ORGANISER_ID, b.RESELLER_ID, b.EVENT_ID, b.COMMISSIONPERC
FROM TABLETICKETS a
INNER JOIN
TORGANISERRESELLER b
on a.ORGANISERRESELLER_ID = b.ORGANISERRESELLER_ID;