/*CUSTOMER TABLE*/

  CREATE TABLE "SYSTEM"."TABLECUSTOMER" 
   (	"CUSTOMER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CUSTOMER_NAME" VARCHAR2(20 BYTE), 
	"CUSTOMER_CONTACT" VARCHAR2(20 BYTE), 
	"CUSTOMER_EMAIL" VARCHAR2(20 BYTE), 
	"TICKET_ID" VARCHAR2(20 BYTE), 
	 CONSTRAINT "TABLECUSTOMER_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "TICKET" FOREIGN KEY ("TICKET_ID")
	  REFERENCES "SYSTEM"."TABLETICKETS" ("TICKET_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  /*EVENT TABLE*/
  
  CREATE TABLE "SYSTEM"."TABLEEVENT" 
   (	"EVENT_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EVENT_TYPE" VARCHAR2(20 BYTE), 
	"EVENT_STARTDATE" DATE, 
	"TICKET_COUNT" NUMBER(*,0), 
	"EVENT_VENUE" VARCHAR2(20 BYTE), 
	"ORGANISERRESELLER_ID" VARCHAR2(20 BYTE), 
	"EVENT_COUNT" NUMBER, 
	 CONSTRAINT "TABLEEVENT_PK" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "EVENYJOIN" FOREIGN KEY ("ORGANISERRESELLER_ID")
	  REFERENCES "SYSTEM"."TORGANISERRESELLER" ("ORGANISERRESELLER_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
 /*ORGANISER TABLE*/
 
  CREATE TABLE "SYSTEM"."TABLEORGANISER" 
   (	"ORGANISER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ORGANISER_NAME" VARCHAR2(20 BYTE), 
	"ORGANISER_CONTACT" NUMBER, 
	"ORGANISER_ADDRESS" VARCHAR2(20 BYTE), 
	 CONSTRAINT "ORGANISERTABLE_PK" PRIMARY KEY ("ORGANISER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  /*RESELLER TABLE*/
   
  CREATE TABLE "SYSTEM"."TABLERESELLER" 
   (	"RESELLER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"RESELLER_NAME" VARCHAR2(20 BYTE), 
	"RESELLER_EMAIL" VARCHAR2(20 BYTE), 
	"RESELLER_CONTACT" NUMBER, 
	"RESELLER_ADDRESS" VARCHAR2(20 BYTE), 
	 CONSTRAINT "TABLERESELLER_PK" PRIMARY KEY ("RESELLER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
 /*TICKETS TABLE*/

  CREATE TABLE "SYSTEM"."TABLETICKETS" 
   (	"TICKET_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TICKET_CATEGORY" VARCHAR2(20 BYTE), 
	"ORGANISERRESELLER_ID" VARCHAR2(20 BYTE), 
	"ROW_ID" NUMBER, 
	"PURCHASE_DATE" DATE, 
	"TICKET_PRICE" NUMBER, 
	 CONSTRAINT "TICKETS_PK" PRIMARY KEY ("TICKET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "ORGRESEL" FOREIGN KEY ("ORGANISERRESELLER_ID")
	  REFERENCES "SYSTEM"."TORGANISERRESELLER" ("ORGANISERRESELLER_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

  CREATE OR REPLACE TRIGGER "SYSTEM"."CUSTOMER_TRIGGER" 
BEFORE INSERT ON TABLETICKETS 
FOR EACH ROW
BEGIN
  SELECT CUSTOMER_SEQNO.nextval
  INTO :new.ROW_ID
  FROM dual;
END;
/
ALTER TRIGGER "SYSTEM"."CUSTOMER_TRIGGER" ENABLE;
 
 /*ORGANISER-RESELLER TABLE*/
 
  CREATE TABLE "SYSTEM"."TORGANISERRESELLER" 
   (	"ORGANISERRESELLER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ORGANISER_ID" VARCHAR2(20 BYTE), 
	"RESELLER_ID" VARCHAR2(20 BYTE), 
	"EVENT_ID" VARCHAR2(20 BYTE), 
	"COMMISSIONPERC" FLOAT(126), 
	 CONSTRAINT "TORGANISERRESELLER_PK" PRIMARY KEY ("ORGANISERRESELLER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "ORG" FOREIGN KEY ("ORGANISER_ID")
	  REFERENCES "SYSTEM"."TABLEORGANISER" ("ORGANISER_ID") ENABLE, 
	 CONSTRAINT "RESEL" FOREIGN KEY ("RESELLER_ID")
	  REFERENCES "SYSTEM"."TABLERESELLER" ("RESELLER_ID") ENABLE, 
	 CONSTRAINT "EVENT" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "SYSTEM"."TABLEEVENT" ("EVENT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;